# Generated by Django 4.0.5 on 2022-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartplugSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=45)),
                ('conn_status', models.IntegerField()),
                ('power', models.IntegerField()),
                ('report_interval', models.IntegerField()),
                ('push_time', models.DateTimeField()),
                ('register_count', models.IntegerField()),
            ],
            options={
                'db_table': 'smartplug_sensor',
                'managed': False,
            },
        ),
    ]
